import { createElement } from 'lwc';
import EqccFormGroupTraining001 from 'c/eqccFormGroupTraining001';

describe('c-eqcc-form-group-training001', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-eqcc-form-group-training001', {
            is: EqccFormGroupTraining001
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});